#version: "3.7"
version: "3"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    hostname: "mysql"
    ports:
      - 3306:3306
    networks:
      - rede-docker
    volumes:
      - dados-bd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: bd_docker
      MYSQL_USER: usr_docker
      MYSQL_PASSWORD: Teste123
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  app:
    image: webdevops/php-apache:alpine-php7
    restart: always
    ports:
      - 8080:80
    networks:
      - rede-docker
    working_dir: /app
    volumes:
      - ./index.php:/app/index.php
    deploy:
      mode: global
#      replicas: 6
      placement:
        constraints: [node.role == worker]
    depends_on:
      - mysql
      - proxy

  proxy:
    image: nginx
    ports:
      - 80:80
    networks:
      - rede-docker
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]

volumes:
  dados-bd:

networks:
  rede-docker:
